runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: portfolio/index.html
  upload: portfolio/index.html

- url: /(.*)
  static_files: portfolio/\1
  upload: portfolio/(.*)
